name: DAST - OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-a'

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report   # <-- nome válido
          path: zap.out      # <-- saída gerada pelo ZAP
