name: SAST - Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan
        run: |
          semgrep --config=p/ci --json > semgrep-report.json
          semgrep --config=p/ci --sarif > semgrep-report.sarif

      - name: Upload report (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-report.sarif
