name: SAST - Semgrep (Static Analysis)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (Semgrep)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install node & npm deps
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Node deps
        run: npm ci

      - name: Install Semgrep CLI
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep (CI rules)
        # usa regras públicas p/ci e as regras locais em .semgrep.yml (se existir)
        run: |
          semgrep --config p/ci --exclude node_modules --sarif semgrep.sarif || true
          # se você tiver regras locais em .semgrep.yml, rode:
          if [ -f .semgrep.yml ]; then semgrep --config .semgrep.yml --exclude node_modules --sarif semgrep_local.sarif || true; fi

      - name: Upload Semgrep SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif

      - name: Upload local Semgrep SARIF (if present)
        if: always() && ( -f semgrep_local.sarif )
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep_local.sarif

      - name: Save Semgrep artifacts (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: |
            semgrep.sarif
            semgrep_local.sarif
