name: DAST - OWASP ZAP Baseline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  zap-baseline:
    name: ZAP Baseline scan
    runs-on: ubuntu-latest
    env:
      TARGET_URL: ${{ secrets.STAGING_URL }} # configure esse secret com a URL de staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate TARGET_URL
        run: |
          if [ -z "${{ secrets.STAGING_URL }}" ]; then
            echo "WARNING: secrets.STAGING_URL is empty. Set the secret or modify the workflow to build & serve web locally."; exit 1
          fi

      - name: Run ZAP baseline scan
        id: zap
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ secrets.STAGING_URL }}
          # token: ${{ secrets.GITHUB_TOKEN }}   # opcional: para criar/atualizar issues
          # cmd_options: '-a'                    # passe -a para atacar (full scan) se quiser
          # rules_file_name: '.zap/rules.tsv'    # se tiver regras de ignore
          fail_action: 'false' # Ajuste: 'true' para falhar workflow em alerts

      - name: Download ZAP report (artifact)
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: zap_scan
          path: ./zap-report || true

      - name: Print summary
        if: always()
        run: |
          echo "ZAP completed. Check workflow logs and repository issues (if configured)."
