name: DAST - OWASP ZAP Baseline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  zap-baseline:
    name: ZAP Baseline scan (local Expo export)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Export Expo app for web
        run: npx expo export

      - name: Start local server
        run: |
          npm install -g http-server
          nohup http-server dist -p 3000 > server.log 2>&1 &

      - name: Wait for server
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server..."
            sleep 5
          done
          echo "Server failed to start"
          exit 1

      - name: Run ZAP baseline scan
        id: zap
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:3000"
          fail_action: false
          cmd_options: '-a -r zap_report.html'

      - name: List zap_scan contents (debug)
        if: always()
        run: ls -R zap_scan || echo "zap_scan directory not found"

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: zap_scan/*.html
